name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Usa a ação oficial na versão v3 que é 100% estável
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Gera um SVG com fundo transparente e a cobra em azul (#3b82f6)
          outputs: |
            dist/github-snake.svg?color_snake=#3b82f6&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
