name: Generate Custom Snake

on:
  schedule:
    # Roda a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

# Permissão obrigatória para evitar o erro de Exit Code 128
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Action customizada com cor e fundo transparente
      - uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake-custom.svg
          snake_color: '#3b82f6' 

      # Atualizado para v4 para evitar o aviso do Node.js
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
